[32m2024-09-09 13:34:49 +1000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - cded0318-e1a7-457f-8632-59fa57e25375 - 40011 - LOGS_CAPTURED - Started capturing logs in process (pid: 40011).
[32m2024-09-09 13:34:49 +1000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - cded0318-e1a7-457f-8632-59fa57e25375 - 40011 - taxi_trips_file - STEP_START - Started execution of step "taxi_trips_file".
[32m2024-09-09 13:34:53 +1000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - cded0318-e1a7-457f-8632-59fa57e25375 - 40011 - taxi_trips_file - STEP_FAILURE - Execution of step "taxi_trips_file" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_trips_file"::

NameError: name 'constants' is not defined

Stack Trace:
  File "/home/lachlan/miniconda3/envs/dagster/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/lachlan/miniconda3/envs/dagster/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 473, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/lachlan/miniconda3/envs/dagster/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/lachlan/miniconda3/envs/dagster/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/home/lachlan/code/dagster_university/dagster_university/assets/trips.py", line 18, in taxi_trips_file
    constants.TAXI_TRIPS_TEMPLATE_FILE_PATH.format(month_to_fetch), "wb"
    ^^^^^^^^^
[0m
