[32m2024-09-09 16:13:14 +1000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB_1 - 011920e8-24fd-4134-9bc2-444e0e43c69b - 233720 - LOGS_CAPTURED - Started capturing logs in process (pid: 233720).
[32m2024-09-09 16:13:14 +1000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB_1 - 011920e8-24fd-4134-9bc2-444e0e43c69b - 233720 - taxi_trips - STEP_START - Started execution of step "taxi_trips".
[32m2024-09-09 16:14:57 +1000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB_1 - 011920e8-24fd-4134-9bc2-444e0e43c69b - 233720 - taxi_trips - STEP_FAILURE - Execution of step "taxi_trips" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_trips"::

duckdb.duckdb.IOException: IO Error: Could not set lock on file "/home/lachlan/code/dagster_university/data/staging/data.duckdb": Conflicting lock is held in /home/lachlan/miniconda3/envs/dagster/bin/python3.12 (PID 212352) by user lachlan. See also https://duckdb.org/docs/connect/concurrency

Stack Trace:
  File "/home/lachlan/miniconda3/envs/dagster/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/lachlan/miniconda3/envs/dagster/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 473, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/lachlan/miniconda3/envs/dagster/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/lachlan/miniconda3/envs/dagster/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lachlan/code/dagster_university/dagster_university/assets/trips.py", line 72, in taxi_trips
    with database.get_connection() as conn:
  File "/home/lachlan/miniconda3/envs/dagster/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/lachlan/miniconda3/envs/dagster/lib/python3.12/site-packages/dagster_duckdb/resource.py", line 51, in get_connection
    conn = backoff(
           ^^^^^^^^
  File "/home/lachlan/miniconda3/envs/dagster/lib/python3.12/site-packages/dagster/_utils/backoff.py", line 70, in backoff
    raise to_raise
  File "/home/lachlan/miniconda3/envs/dagster/lib/python3.12/site-packages/dagster/_utils/backoff.py", line 64, in backoff
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
[0m
